package com.archery.jdbc.internal;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 * Connection 实现：无状态 HTTP 客户端的持有者。
 * <p>
 * 只读 SELECT 语义下的映射约定：
 * <ul>
 *   <li>事务方法（setAutoCommit/commit/rollback 等）为 no-op —— SELECT 无事务语义，
 *       保持宽容以兼容会调用它们的 BI 工具</li>
 *   <li>catalog = MySQL database（setCatalog 切换默认库）</li>
 *   <li>连接不可跨线程并发使用（JDBC 规范即如此约定）</li>
 * </ul>
 */
public class ArcheryConnection implements Connection {

  final ArcheryUrl url;
  private final ArcheryHttpClient client;
  private final List<Statement> statements = new ArrayList<>();

  private volatile String currentDb;
  private volatile boolean closed;

  public ArcheryConnection(ArcheryUrl url) throws SQLException {
    this.url = url;
    this.client = new ArcheryHttpClient(url);
    this.currentDb = url.dbName;
    if (!url.lazyLogin) {
      // 默认 fail-fast：连接建立时即认证；lazyLogin=true 时推迟到首次查询
      this.client.login(url.user, url.password);
    }
  }

  ArcheryHttpClient client() {
    return client;
  }

  String instanceName() {
    return url.instanceName;
  }

  String currentDb() {
    return currentDb;
  }

  int defaultLimit() {
    return url.defaultLimit;
  }

  void register(Statement stmt) {
    synchronized (statements) {
      statements.add(stmt);
    }
  }

  void unregister(Statement stmt) {
    synchronized (statements) {
      statements.remove(stmt);
    }
  }

  void checkOpen() throws SQLException {
    if (closed) {
      throw new SQLException("连接已关闭", "08003");
    }
  }

  // ------------------------------------------------------------ Statement 创建

  @Override
  public Statement createStatement() throws SQLException {
    checkOpen();
    ArcheryStatement stmt = new ArcheryStatement(this);
    register(stmt);
    return stmt;
  }

  @Override
  public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
    return createStatement(resultSetType, resultSetConcurrency, java.sql.ResultSet.CLOSE_CURSORS_AT_COMMIT);
  }

  @Override
  public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability)
      throws SQLException {
    checkOpen();
    // 结果集全量物化：FORWARD_ONLY 与 SCROLL_INSENSITIVE 等价支持；SENSITIVE/UPDATABLE 不支持
    if (resultSetType != ResultSet.TYPE_FORWARD_ONLY
        && resultSetType != ResultSet.TYPE_SCROLL_INSENSITIVE) {
      throw new SQLFeatureNotSupportedException(
          "不支持的结果集类型: " + resultSetType + "（仅 TYPE_FORWARD_ONLY / TYPE_SCROLL_INSENSITIVE）", "HY106");
    }
    if (resultSetConcurrency != ResultSet.CONCUR_READ_ONLY) {
      throw new SQLFeatureNotSupportedException("不支持的结果集并发模式: " + resultSetConcurrency, "HY107");
    }
    ArcheryStatement stmt = new ArcheryStatement(this);
    register(stmt);
    return stmt;
  }

  @Override
  public PreparedStatement prepareStatement(String sql) throws SQLException {
    checkOpen();
    ArcheryPreparedStatement stmt = new ArcheryPreparedStatement(this, sql);
    register(stmt);
    return stmt;
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency)
      throws SQLException {
    return prepareStatement(sql);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency,
      int resultSetHoldability) throws SQLException {
    return prepareStatement(sql);
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
    throw unsupported("prepareStatement(Statement.RETURN_GENERATED_KEYS)");
  }

  @Override
  public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
    throw unsupported("prepareStatement(int[])");
  }

  @Override
  public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
    throw unsupported("prepareStatement(String[])");
  }

  @Override
  public CallableStatement prepareCall(String sql) throws SQLException {
    throw unsupported("prepareCall");
  }

  @Override
  public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
    throw unsupported("prepareCall");
  }

  @Override
  public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
      int resultSetHoldability) throws SQLException {
    throw unsupported("prepareCall");
  }

  @Override
  public String nativeSQL(String sql) throws SQLException {
    return sql;
  }

  // ------------------------------------------------------------ 事务（no-op）

  @Override
  public void setAutoCommit(boolean autoCommit) {
    // no-op：SELECT-only，无事务语义；宽容处理以兼容 BI 工具
  }

  @Override
  public boolean getAutoCommit() {
    return true;
  }

  @Override
  public void commit() {
    // no-op
  }

  @Override
  public void rollback() {
    // no-op
  }

  @Override
  public void rollback(Savepoint savepoint) {
    // no-op
  }

  @Override
  public void setReadOnly(boolean readOnly) {
    // 本驱动恒为只读，忽略
  }

  @Override
  public boolean isReadOnly() {
    return true;
  }

  @Override
  public void setTransactionIsolation(int level) {
    // no-op
  }

  @Override
  public int getTransactionIsolation() {
    return TRANSACTION_NONE;
  }

  // ------------------------------------------------------------ catalog / schema

  @Override
  public void setCatalog(String catalog) throws SQLException {
    checkOpen();
    if (catalog != null && !catalog.isEmpty()) {
      this.currentDb = catalog;
    }
  }

  @Override
  public String getCatalog() {
    return currentDb;
  }

  @Override
  public void setSchema(String schema) {
    // MySQL 无 schema 概念
  }

  @Override
  public String getSchema() {
    return null;
  }

  @Override
  public java.util.Map<String, Class<?>> getTypeMap() {
    return new java.util.HashMap<>();
  }

  @Override
  public void setTypeMap(java.util.Map<String, Class<?>> map) throws SQLException {
    throw unsupported("setTypeMap");
  }

  // ------------------------------------------------------------ 元数据 / 生命周期

  @Override
  public DatabaseMetaData getMetaData() {
    return new ArcheryDatabaseMetaData(this);
  }

  @Override
  public void close() throws SQLException {
    if (closed) {
      return;
    }
    closed = true;
    List<Statement> toClose;
    synchronized (statements) {
      toClose = new ArrayList<>(statements);
    }
    for (Statement stmt : toClose) {
      try {
        stmt.close();
      }
      catch (SQLException ignore) {
        // 尽力关闭
      }
    }
    statements.clear();
    // best-effort 登出，避免遗留服务端会话（失败静默忽略）
    client.logout();
  }

  @Override
  public boolean isClosed() {
    return closed;
  }

  @Override
  public boolean isValid(int timeout) throws SQLException {
    if (closed) {
      return false;
    }
    try {
      Statement stmt = createStatement();
      try {
        stmt.executeQuery("SELECT 1").close();
      }
      finally {
        stmt.close();
      }
      return true;
    }
    catch (SQLException e) {
      return false;
    }
  }

  @Override
  public void abort(Executor executor) throws SQLException {
    close();
  }

  // ------------------------------------------------------------ 其余 API

  @Override
  public SQLWarning getWarnings() {
    return null;
  }

  @Override
  public void clearWarnings() {
    // 无 warning 通道
  }

  @Override
  public void setHoldability(int holdability) {
    // no-op
  }

  @Override
  public int getHoldability() {
    return java.sql.ResultSet.CLOSE_CURSORS_AT_COMMIT;
  }

  @Override
  public Savepoint setSavepoint() throws SQLException {
    throw unsupported("setSavepoint");
  }

  @Override
  public Savepoint setSavepoint(String name) throws SQLException {
    throw unsupported("setSavepoint");
  }

  @Override
  public void releaseSavepoint(Savepoint savepoint) {
    // no-op
  }

  @Override
  public void setNetworkTimeout(Executor executor, int milliseconds) {
    client.setReadTimeoutMs(milliseconds);
  }

  @Override
  public int getNetworkTimeout() {
    return client.getReadTimeoutMs();
  }

  @Override
  public Properties getClientInfo() {
    return new Properties();
  }

  @Override
  public void setClientInfo(String name, String value) {
    // 忽略
  }

  @Override
  public void setClientInfo(Properties properties) throws SQLClientInfoException {
    // 忽略
  }

  @Override
  public String getClientInfo(String name) {
    return null;
  }

  @Override
  public Clob createClob() throws SQLException {
    throw unsupported("createClob");
  }

  @Override
  public Blob createBlob() throws SQLException {
    throw unsupported("createBlob");
  }

  @Override
  public NClob createNClob() throws SQLException {
    throw unsupported("createNClob");
  }

  @Override
  public SQLXML createSQLXML() throws SQLException {
    throw unsupported("createSQLXML");
  }

  @Override
  public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
    throw unsupported("createArrayOf");
  }

  @Override
  public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
    throw unsupported("createStruct");
  }

  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    if (iface.isInstance(this)) {
      return iface.cast(this);
    }
    throw new SQLException("不支持 unwrap: " + iface.getName(), "HY000");
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) {
    return iface.isInstance(this);
  }

  private static SQLException unsupported(String api) {
    return new SQLFeatureNotSupportedException("只读驱动不支持: " + api, "0A000");
  }
}
