package com.archery.jdbc.internal;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLFeatureNotSupportedException;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * Statement 实现：executeQuery → POST /query/。
 * <p>
 * 行为约定：
 * <ul>
 *   <li>行数上限 = setMaxRows()（&gt;0 时），否则取 URL 的 limit 参数</li>
 *   <li>setQueryTimeout 仅记录（服务端有全局 max_execution_time 保护）</li>
 *   <li>setFetchSize 无流式游标，仅记录</li>
 *   <li>executeUpdate / executeBatch 等写操作抛异常（只读驱动）</li>
 * </ul>
 */
public class ArcheryStatement implements Statement {

  protected final ArcheryConnection conn;

  private int maxRows;
  private int queryTimeoutSeconds;
  private int fetchSize;
  private int fetchDirection = ResultSet.FETCH_FORWARD;
  private boolean closed;
  protected ResultSet currentResultSet;
  protected QueryResult currentResult;

  ArcheryStatement(ArcheryConnection conn) {
    this.conn = conn;
  }

  protected void checkOpen() throws SQLException {
    conn.checkOpen();
    if (closed) {
      throw new SQLException("Statement 已关闭", "HY010");
    }
  }

  QueryResult executeQueryInternal(String sql, int limit) throws SQLException {
    return conn.client().query(conn.instanceName(), conn.currentDb(), sql, limit);
  }

  protected ResultSet executeAndWrap(String sql, int limit) throws SQLException {
    closeCurrentResultSet();
    currentResult = executeQueryInternal(sql, limit);
    currentResultSet = new ArcheryResultSet(this, currentResult);
    return currentResultSet;
  }

  private void closeCurrentResultSet() throws SQLException {
    if (currentResultSet != null) {
      try {
        currentResultSet.close();
      }
      finally {
        currentResultSet = null;
        currentResult = null;
      }
    }
  }

  // ------------------------------------------------------------ 查询执行

  @Override
  public ResultSet executeQuery(String sql) throws SQLException {
    checkOpen();
    return executeAndWrap(sql, effectiveLimit());
  }

  @Override
  public boolean execute(String sql) throws SQLException {
    checkOpen();
    executeAndWrap(sql, effectiveLimit());
    return currentResult != null && currentResult.columnCount() > 0;
  }

  @Override
  public ResultSet getResultSet() {
    return currentResultSet;
  }

  @Override
  public int getUpdateCount() {
    return -1; // 只读驱动：恒为结果集
  }

  @Override
  public boolean getMoreResults() {
    return false;
  }

  @Override
  public boolean getMoreResults(int current) {
    return false;
  }

  @Override
  public int[] executeBatch() throws SQLException {
    throw new SQLFeatureNotSupportedException("只读驱动不支持 executeBatch", "0A000");
  }

  @Override
  public long[] executeLargeBatch() throws SQLException {
    throw new SQLFeatureNotSupportedException("只读驱动不支持 executeLargeBatch", "0A000");
  }

  @Override
  public int executeUpdate(String sql) throws SQLException {
    throw new SQLException("只读驱动仅支持 SELECT，不支持: " + abbreviate(sql), "HY000");
  }

  @Override
  public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    return executeUpdate(sql);
  }

  @Override
  public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
    return executeUpdate(sql);
  }

  @Override
  public int executeUpdate(String sql, String[] columnNames) throws SQLException {
    return executeUpdate(sql);
  }

  @Override
  public long executeLargeUpdate(String sql) throws SQLException {
    return executeUpdate(sql);
  }

  @Override
  public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
    return executeUpdate(sql);
  }

  @Override
  public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
    return executeUpdate(sql);
  }

  @Override
  public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
    return executeUpdate(sql);
  }

  @Override
  public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
    return execute(sql);
  }

  @Override
  public boolean execute(String sql, int[] columnIndexes) throws SQLException {
    return execute(sql);
  }

  @Override
  public boolean execute(String sql, String[] columnNames) throws SQLException {
    return execute(sql);
  }

  @Override
  public int getFetchDirection() {
    return fetchDirection;
  }

  @Override
  public void setFetchDirection(int direction) throws SQLException {
    if (direction != ResultSet.FETCH_FORWARD && direction != ResultSet.FETCH_REVERSE
        && direction != ResultSet.FETCH_UNKNOWN) {
      throw new SQLException("非法 fetchDirection: " + direction, "HY000");
    }
    this.fetchDirection = direction;
  }

  // ------------------------------------------------------------ 属性

  @Override
  public void setMaxRows(int max) throws SQLException {
    if (max < 0) {
      throw new SQLException("maxRows 不能为负数", "HY000");
    }
    this.maxRows = max;
  }

  @Override
  public int getMaxRows() {
    return maxRows;
  }

  @Override
  public int getMaxFieldSize() {
    return 0;
  }

  @Override
  public void setMaxFieldSize(int max) {
    // 不限制
  }

  @Override
  public void setQueryTimeout(int seconds) throws SQLException {
    if (seconds < 0) {
      throw new SQLException("queryTimeout 不能为负数", "HY000");
    }
    this.queryTimeoutSeconds = seconds;
  }

  @Override
  public int getQueryTimeout() {
    return queryTimeoutSeconds;
  }

  @Override
  public void setFetchSize(int rows) {
    this.fetchSize = rows;
  }

  @Override
  public int getFetchSize() {
    return fetchSize;
  }

  @Override
  public void setEscapeProcessing(boolean enable) {
    // 无需转义处理
  }

  @Override
  public void setCursorName(String name) {
    // 无游标概念
  }

  @Override
  public void addBatch(String sql) throws SQLException {
    throw new SQLFeatureNotSupportedException("只读驱动不支持 addBatch", "0A000");
  }

  @Override
  public void clearBatch() {
    // 无批次
  }

  @Override
  public boolean isPoolable() {
    return false;
  }

  @Override
  public void setPoolable(boolean poolable) {
    // 无语句池
  }

  @Override
  public int getResultSetType() {
    return ResultSet.TYPE_SCROLL_INSENSITIVE;
  }

  @Override
  public int getResultSetConcurrency() {
    return ResultSet.CONCUR_READ_ONLY;
  }

  @Override
  public int getResultSetHoldability() {
    return ResultSet.CLOSE_CURSORS_AT_COMMIT;
  }

  // ------------------------------------------------------------ 结果附加信息

  @Override
  public ResultSet getGeneratedKeys() throws SQLException {
    throw new SQLFeatureNotSupportedException("只读驱动不支持 getGeneratedKeys", "0A000");
  }

  @Override
  public SQLWarning getWarnings() {
    return null;
  }

  @Override
  public void clearWarnings() {
    // 无 warning 通道
  }

  // ------------------------------------------------------------ 生命周期

  @Override
  public void close() throws SQLException {
    if (closed) {
      return;
    }
    closed = true;
    closeCurrentResultSet();
    conn.unregister(this);
  }

  @Override
  public boolean isClosed() {
    return closed;
  }

  @Override
  public boolean isCloseOnCompletion() {
    return false;
  }

  @Override
  public void closeOnCompletion() {
    // 不支持
  }

  @Override
  public void cancel() {
    // HTTP 无取消通道；服务端有 max_execution_time + kill 连接保护
  }

  @Override
  public Connection getConnection() {
    return conn;
  }

  @Override
  public <T> T unwrap(Class<T> iface) throws SQLException {
    if (iface.isInstance(this)) {
      return iface.cast(this);
    }
    throw new SQLException("不支持 unwrap: " + iface.getName(), "HY000");
  }

  @Override
  public boolean isWrapperFor(Class<?> iface) {
    return iface.isInstance(this);
  }

  protected int effectiveLimit() {
    return maxRows > 0 ? maxRows : conn.defaultLimit();
  }

  private static String abbreviate(String s) {
    if (s == null) {
      return "";
    }
    return s.length() > 120 ? s.substring(0, 120) + "..." : s;
  }
}
